### ISSUE TITLE
Feature Request: Support hiding to tray/menubar 

### ISSUE THREAD

**Issue by BlackHoleFox** [heyman/heynote#32] opened 2023-12-22 20:49 UTC
Hiyo there, this app is great so far, great work.

My feature request would help Heynote fit nicely into my "summonable scratchpad" workflow by supporting hiding the open window (and on Windows/Linux, the taskbar entry) behind either a tray icon on Windows or a menubar icon on macOS. When hidden, it wouldn't show up in the Alt+Tab menu, but it could be toggled visible/invisible via either clicking the icon or using the global keyboard shortcut.

1Password 8, KeePassXC, and Thunderbird (on Windows) support behaviors like this if existing references are useful.

**Comment by felipelube** [comment] 2023-12-22 22:36
I find it useful. But do we want this @heyman? I'm happy to take this one.

**Comment by Victor239** [comment] 2023-12-23 10:05
In addition it'd be great if there was an option that when closing the window it wouldn't exit, it would simply hide to tray (like KeePassXC).

**Comment by rmccue** [comment] 2024-01-25 17:46
Fixed in https://github.com/heyman/heynote/pull/90 ?

**Comment by delfuego** [comment] 2024-01-25 18:26
#90 definitely adds some nice functionality to address this! I'd ask that maybe that functionality be modified a bit, though — maybe make it so that if you have HeyNote in the menu bar, when you left-click (primary-click) on the icon it opens the HeyNote window, and then the current click behavior (showing a menu that lets you open the window or access any of the typical menu items) is moved to right-click behavior instead. This would be similar to a lot of other menubar-living apps, like 1Password, Scrap Paper, etc.

**Comment by heyman** [comment] 2024-01-25 22:01
> #90 definitely adds some nice functionality to address this! I'd ask that maybe that functionality be modified a bit, though — maybe make it so that if you have HeyNote in the menu bar, when you left-click (primary-click) on the icon, it opens the HeyNote window, and then the current click behavior (showing a menu that lets you open the window or access any of the typical menu items) is moved to right-click behavior instead. 

On Windows, that *is* the current behaviour. On Mac - which I suspect you're talking about since you mention "menu bar" - left click opens a menu. The reason for that is both that it seems to be quite a common behaviour, and also because otherwise there is no way to access the application menu when Heynote isn't shown in the dock. Out of my six programs in the menu bar, four of them open a menu when left clicked (1password, iterm2, Docker and Grammarly).

> This would be similar to a lot of other menubar-living apps, like 1Password, Scrap Paper, etc.

Weird, when I left click 1Password in the menu bar, it just shows a menu,

**Comment by delfuego** [comment] 2024-01-25 22:28
How funny — it looks like 1Password launches the app if it's not already open/visible, but if it is, it shows a menu! Or at least that's the behavior I'm seeing.

And note that I'm saying a RIGHT click would open the menu; for 1Password (with the above caveat), and for Scrap Paper (the app I'm hopeful HeyNote will replace!), that's what they do.

**Comment by BlackHoleFox** [comment] 2024-01-25 22:36
The Windows side of this is basically what I'd expect but the macOS half feels rough still for some reason. I don't know if its because the window doesn't respond to Command+H or what.

> How funny — it looks like 1Password launches the app if it's not already open/visible, but if it is, it shows a menu! Or at least that's the behavior I'm seeing.

Its a configurable setting. Mine pops open their floating palette:

<img width="486" alt="image" src="https://github.com/heyman/heynote/assets/20936452/f470526c-adf2-46ba-a13c-3cdf0bf3a5d5">

**Comment by rmccue** [comment] 2024-01-25 22:47
I’d agree on the expected behaviour being that left click opens the app. The primary action I want when app isn’t already visible is to take a note.

In the other apps I have where left clicking opens a menu, it’s either because there are multiple primary actions to select from (eg ClearShot X) or the action itself is the menu (Dato, built-in Control Centre, Wi-Fi). Those with a menu also have a select number of controls, rather than the full menu where most of the options only make sense with the window in focus (Edit, View, Window, and to a degree Help).

**Comment by heyman** [comment] 2024-01-26 00:42
> And note that I'm saying a RIGHT click would open the menu

Oh, of course :)

> The primary action I want when app isn’t already visible is to take a note.

Yeah, that's a good argument.

**Comment by heyman** [comment] 2024-01-26 00:43
The Mac behaviour has now been fixed in a5088a48af40845a271209379faeea3ba9e4a3cc

**Closed** 2024-01-26 00:44 UTC
